
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import java.util.ArrayList;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alexpieprzycki
 * THIS FILE HOUSES MOUSE LISTENERS
 * Mouse stuff:
 *      The listeners here collect mouse data
 *      Then the mouse data is sent off to the right method where magic happens.
 *      Ex. Mouse motion listener sends mouse position to gameboard
 */
public class GameView extends javax.swing.JPanel implements MouseMotionListener{
    
    private static ArrayList<Battleship> list;
    private GameBoard game1;
    private static JFrame frame;
    private int x = 0;
    private int y = 0;
    private long clickCount = 0;
    private long clickCountOld = 0;
    /**
     * Creates new form GameView
     */
    
    public GameView(ArrayList<Battleship> battle) {
        list = battle;
        addMouseMotionListener(this);
        initComponents();
    }
    public void mouseMoved(MouseEvent e){//Might need to create a sensitivity range (so like the mouse needs to move a couple pixels for listener to pick up)
        x = e.getX();
        y = e.getY();
        repaint();
    }
    public void mouseDragged (MouseEvent e){
        
    }
    public void addShip(Battleship battle){
        list.add(battle);
        repaint();
    }
    
    public void update(){
        repaint();
    }

    public void paintComponent(Graphics g){
        //System.out.println("hi");
        super.paintComponent(g);
        System.out.println(x + y);
        game1 = new GameBoard(list,x,y);
        game1.drawMouseMovement(g);
        if(clickCount != clickCountOld){
            game1.drawBoard(g);
            clickCountOld++;
        }
        
    }
    
    public static void main(String[] args) {
        frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);       
        frame.getContentPane().add(new GameView(list));
        frame.pack();
        frame.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("MOVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(621, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(572, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clickCount++;
        update();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
